openapi: 3.0.3
info:
  title: Basic Rest API
  description: This Microservice API is created using serverless framework on AWS to demonstrate CURD operations of a basic Rest API.
  version: "1.0"
servers:
- url: http://localhost:3000/dev
  description: local
- url: https://URL.us-west-2.amazonaws.com
  description: remote <TBD>
paths:
  /v1/results:
    get:
      tags:
      - Get API.
      summary: Serving  all results.
      description: API end point to serve all results.
      responses:
        "200":
          description: OK
          content:
            application/json;:
              schema:
                $ref: '#/components/schemas/getResults'
        "500":
          $ref: '#/components/responses/500'
components:
  schemas:
    getResults:
      type: array
      description: List of all results.
      items:
        type: string
        description: A particular result.
        example: 'First'
  responses:
    "201":
      description: Created
    "400":
      description: Bad Request
      content:
        text/plain:
          schema:
            type: string
            description: Error message
            example: Invalid Input
    "401":
      description: Unauthorized
      content:
        text/plain:
          schema:
            type: string
            description: Error message
            example: Not Authorized
    "500":
      description: Internal Server Error
      content:
        text/plain:
          schema:
            type: string
            description: Error message
            example: Server Error
